[package]
name = "helloworld"
version = "0.1.1"
edition = "2021"

[dependencies]
rand = "0.8.5"
reqwest = { version = "0.12.5", features = ["blocking", "json"] }
dotenv = "0.15"
etcetera = "0.8.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0.63"
